// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System.Text.Json.Serialization;

namespace Microsoft.StoreServices.DisplayCatalog.Product
{
    public class AlternateId2
    {
        [JsonPropertyName("IdType")]
        public string IdType;

        [JsonPropertyName("Value")]
        public string Value;
    }
}