// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System.Text.Json.Serialization;

namespace Microsoft.StoreServices.DisplayCatalog.Product
{
    public class Application
    {
        [JsonPropertyName("ApplicationId")]
        public string ApplicationId;

        [JsonPropertyName("DeclarationOrder")]
        public int DeclarationOrder;

        [JsonPropertyName("Extensions")]
        public string[] Extensions;
    }
}