// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System.Text.Json.Serialization;

namespace Microsoft.StoreServices.DisplayCatalog.Product
{
    public class Attribute
    {
        [JsonPropertyName("Name")]
        public string Name;

        [JsonPropertyName("Minimum")]
        public int? Minimum;

        [JsonPropertyName("Maximum")]
        public int? Maximum;

        [JsonPropertyName("ApplicablePlatforms")]
        public string[] ApplicablePlatforms;

        [JsonPropertyName("Group")]
        public string Group;
    }
}