// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System.Text.Json.Serialization;

namespace Microsoft.StoreServices.DisplayCatalog.Product
{
    public class Availability
    {
        [JsonPropertyName("Actions")]
        public string[] Actions;

        [JsonPropertyName("AvailabilityASchema")]
        public string AvailabilityASchema;

        [JsonPropertyName("AvailabilityBSchema")]
        public string AvailabilityBSchema;

        [JsonPropertyName("AvailabilityId")]
        public string AvailabilityId;

        [JsonPropertyName("Conditions")]
        public Conditions Conditions;

        [JsonPropertyName("LastModifiedDate")]
        public string LastModifiedDate;

        [JsonPropertyName("Markets")]
        public string[] Markets;

        [JsonPropertyName("OrderManagementData")]
        public OrderManagementData OrderManagementData;

        [JsonPropertyName("Properties")]
        public Properties3 Properties;

        [JsonPropertyName("SkuId")]
        public string SkuId;

        [JsonPropertyName("DisplayRank")]
        public int DisplayRank;

        [JsonPropertyName("RemediationRequired")]
        public bool RemediationRequired;

        [JsonPropertyName("Remediations")]
        public Remediation2[] Remediations;

        [JsonPropertyName("LicensingData")]
        public LicensingData LicensingData;

        [JsonPropertyName("AlternateIds")]
        public AlternateId2[] AlternateIds;
    }
}