// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System.Text.Json.Serialization;

namespace Microsoft.StoreServices.DisplayCatalog.Product
{
    public class BundleConfig
    {
        [JsonPropertyName("BundleId")]
        public string BundleId;

        [JsonPropertyName("RenderHint")]
        public string RenderHint;

        [JsonPropertyName("StartingFromAmount")]
        public StartingFromAmount StartingFromAmount;

        [JsonPropertyName("SaveUpTo")]
        public SaveUpTo SaveUpTo;

        [JsonPropertyName("BundleSlots")]
        public BundleSlot[] BundleSlots;

        [JsonPropertyName("LocalizedProperties")]
        public LocalizedProperty3[] LocalizedProperties;
    }
}