// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System.Text.Json.Serialization;

namespace Microsoft.StoreServices.DisplayCatalog.Product
{
    public class BundleSlot
    {
        [JsonPropertyName("SlotId")]
        public int SlotId;

        [JsonPropertyName("Minimum")]
        public int Minimum;

        [JsonPropertyName("Maximum")]
        public int Maximum;

        [JsonPropertyName("DisplayRank")]
        public int DisplayRank;

        [JsonPropertyName("RenderHint")]
        public string RenderHint;

        [JsonPropertyName("ChildIdentifiers")]
        public ChildIdentifier[] ChildIdentifiers;

        [JsonPropertyName("LocalizedProperties")]
        public LocalizedProperty2[] LocalizedProperties;
    }
}