// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System.Text.Json.Serialization;

namespace Microsoft.StoreServices.DisplayCatalog.Product
{
    public class BundledSku
    {
        [JsonPropertyName("BigId")]
        public string BigId;

        [JsonPropertyName("DisplayRank")]
        public int DisplayRank;

        [JsonPropertyName("IsPrimary")]
        public bool IsPrimary;

        [JsonPropertyName("FulfillmentType")]
        public object FulfillmentType;
    }
}