// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System.Text.Json.Serialization;

namespace Microsoft.StoreServices.DisplayCatalog.Product
{
    public class ChildIdentifier
    {
        [JsonPropertyName("AutoSelected")]
        public bool AutoSelected;

        [JsonPropertyName("DefaultSelected")]
        public bool DefaultSelected;

        [JsonPropertyName("ProductId")]
        public string ProductId;

        [JsonPropertyName("SkuId")]
        public string SkuId;

        [JsonPropertyName("AvailabilityId")]
        public string AvailabilityId;

        [JsonPropertyName("Tag")]
        public string Tag;

        [JsonPropertyName("DisplayRank")]
        public int DisplayRank;
    }
}