// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System.Text.Json.Serialization;

namespace Microsoft.StoreServices.DisplayCatalog.Product
{
    public class ConfigurationReference
    {
        [JsonPropertyName("Key")]
        public string Key;

        [JsonPropertyName("Value")]
        public string Value;
    }
}