// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System.Text.Json.Serialization;

namespace Microsoft.StoreServices.DisplayCatalog.Product
{
    public class ContentRating
    {
        [JsonPropertyName("RatingSystem")]
        public string RatingSystem;

        [JsonPropertyName("RatingId")]
        public string RatingId;

        [JsonPropertyName("RatingDescriptors")]
        public string[] RatingDescriptors;

        [JsonPropertyName("RatingDisclaimers")]
        public object[] RatingDisclaimers;

        [JsonPropertyName("InteractiveElements")]
        public string[] InteractiveElements;
    }
}