// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System.Text.Json.Serialization;

namespace Microsoft.StoreServices.DisplayCatalog.Product
{
    public class Dimensions
    {
        [JsonPropertyName("Length")]
        public double Length;

        [JsonPropertyName("Width")]
        public double Width;

        [JsonPropertyName("Height")]
        public double Height;

        [JsonPropertyName("Weight")]
        public double Weight;

        [JsonPropertyName("SystemOfMeasurement")]
        public string SystemOfMeasurement;
    }
}