// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System.Text.Json.Serialization;

namespace Microsoft.StoreServices.DisplayCatalog.Product
{
    public class DisplaySkuAvailability
    {
        [JsonPropertyName("Sku")]
        public Sku Sku;

        [JsonPropertyName("Availabilities")]
        public Availability[] Availabilities;
    }
}