// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System.Text.Json.Serialization;

namespace Microsoft.StoreServices.DisplayCatalog.Product
{
    public class Distributions
    {
        [JsonPropertyName("UPC")]
        public object UPC;

        [JsonPropertyName("EAN")]
        public object EAN;

        [JsonPropertyName("JAN")]
        public object JAN;
    }
}