// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System.Text.Json.Serialization;

namespace Microsoft.StoreServices.DisplayCatalog.Product
{
    public class EligibilityProperties
    {
        [JsonPropertyName("Affirmations")]
        public object[] Affirmations;

        [JsonPropertyName("Remediations")]
        public Remediation[] Remediations;
    }
}