// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System.Text.Json.Serialization;

namespace Microsoft.StoreServices.DisplayCatalog.Product
{
    public class ExternalSource
    {
        [JsonPropertyName("Name")]
        public string Name;

        [JsonPropertyName("ID")]
        public string ID;
    }
}