// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System.Text.Json.Serialization;

namespace Microsoft.StoreServices.DisplayCatalog.Product
{
    public class FrameworkDependency
    {
        /*[JsonPropertyName("MaxTested")]
        public BigInteger MaxTested;

        [JsonPropertyName("MinVersion")]
        public BigInteger MinVersion;*/

        [JsonPropertyName("PackageIdentity")]
        public string PackageIdentity;
    }
}