// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System.Text.Json.Serialization;

namespace Microsoft.StoreServices.DisplayCatalog.Product
{
    public class HardwareProperties
    {
        [JsonPropertyName("MinimumHardware")]
        public string[] MinimumHardware;

        [JsonPropertyName("RecommendedHardware")]
        public string[] RecommendedHardware;

        [JsonPropertyName("MinimumProcessor")]
        public string MinimumProcessor;

        [JsonPropertyName("RecommendedProcessor")]
        public string RecommendedProcessor;

        [JsonPropertyName("MinimumGraphics")]
        public string MinimumGraphics;

        [JsonPropertyName("RecommendedGraphics")]
        public string RecommendedGraphics;
    }
}