// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System.Text.Json.Serialization;

namespace Microsoft.StoreServices.DisplayCatalog.Product
{
    public class LegalText
    {
        [JsonPropertyName("AdditionalLicenseTerms")]
        public string AdditionalLicenseTerms;

        [JsonPropertyName("Copyright")]
        public string Copyright;

        [JsonPropertyName("CopyrightUri")]
        public string CopyrightUri;

        [JsonPropertyName("PrivacyPolicy")]
        public string PrivacyPolicy;

        [JsonPropertyName("PrivacyPolicyUri")]
        public string PrivacyPolicyUri;

        [JsonPropertyName("Tou")]
        public string Tou;

        [JsonPropertyName("TouUri")]
        public string TouUri;
    }
}