// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System.Text.Json.Serialization;

namespace Microsoft.StoreServices.DisplayCatalog.Product
{
    public class LocalizedProperty4
    {
        [JsonPropertyName("Contributors")]
        public object[] Contributors;

        [JsonPropertyName("Features")]
        public string[] Features;

        [JsonPropertyName("MinimumNotes")]
        public string MinimumNotes;

        [JsonPropertyName("RecommendedNotes")]
        public string RecommendedNotes;

        [JsonPropertyName("ReleaseNotes")]
        public string ReleaseNotes;

        [JsonPropertyName("DisplayPlatformProperties")]
        public object DisplayPlatformProperties;

        [JsonPropertyName("SkuDescription")]
        public string SkuDescription;

        [JsonPropertyName("SkuTitle")]
        public string SkuTitle;

        [JsonPropertyName("SkuButtonTitle")]
        public string SkuButtonTitle;

        [JsonPropertyName("DeliveryDateOverlay")]
        public string DeliveryDateOverlay;

        [JsonPropertyName("SkuDisplayRank")]
        public SkuDisplayRank[] SkuDisplayRank;

        [JsonPropertyName("TextResources")]
        public object[] TextResources;

        [JsonPropertyName("Images")]
        public Image2[] Images;

        [JsonPropertyName("LegalText")]
        public LegalText LegalText;

        [JsonPropertyName("Language")]
        public string Language;

        [JsonPropertyName("Markets")]
        public string[] Markets;

        [JsonPropertyName("Disclaimers")]
        public object[] Disclaimers;

        [JsonPropertyName("Specifications")]
        public object[] Specifications;

        [JsonPropertyName("WebBlendsData")]
        public WebBlendsData WebBlendsData;
    }
}