// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System.Text.Json.Serialization;

namespace Microsoft.StoreServices.DisplayCatalog.Product
{
    public class LocalizedProperty2
    {
        [JsonPropertyName("SlotTitle")]
        public string SlotTitle;

        [JsonPropertyName("Images")]
        public object Images;

        [JsonPropertyName("Language")]
        public string Language;

        [JsonPropertyName("Markets")]
        public string[] Markets;
    }
}