// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System.Text.Json.Serialization;

namespace Microsoft.StoreServices.DisplayCatalog.Product
{
    public class LocalizedProperty3
    {
        [JsonPropertyName("BundleTitle")]
        public string BundleTitle;

        [JsonPropertyName("Description")]
        public string Description;

        [JsonPropertyName("ShortDescription")]
        public string ShortDescription;

        [JsonPropertyName("Language")]
        public string Language;

        [JsonPropertyName("Markets")]
        public string[] Markets;
    }
}