// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System.Text.Json.Serialization;

namespace Microsoft.StoreServices.DisplayCatalog.Product
{
    public class LocalizedProperty
    {
        [JsonPropertyName("DeveloperName")]
        public string DeveloperName;

        [JsonPropertyName("DisplayPlatformProperties")]
        public object DisplayPlatformProperties;

        [JsonPropertyName("PublisherName")]
        public string PublisherName;

        [JsonPropertyName("PublisherWebsiteUri")]
        public string PublisherWebsiteUri;

        [JsonPropertyName("SupportUri")]
        public string SupportUri;

        [JsonPropertyName("EligibilityProperties")]
        public EligibilityProperties EligibilityProperties;

        [JsonPropertyName("Franchises")]
        public object[] Franchises;

        [JsonPropertyName("Images")]
        public Image[] Images;

        [JsonPropertyName("Videos")]
        public Video[] Videos;

        [JsonPropertyName("ProductDescription")]
        public string ProductDescription;

        [JsonPropertyName("ProductTitle")]
        public string ProductTitle;

        [JsonPropertyName("ShortTitle")]
        public string ShortTitle;

        [JsonPropertyName("SortTitle")]
        public string SortTitle;

        [JsonPropertyName("FriendlyTitle")]
        public object FriendlyTitle;

        [JsonPropertyName("ShortDescription")]
        public string ShortDescription;

        [JsonPropertyName("SearchTitles")]
        public SearchTitle[] SearchTitles;

        [JsonPropertyName("VoiceTitle")]
        public string VoiceTitle;

        [JsonPropertyName("RenderGroupDetails")]
        public object RenderGroupDetails;

        [JsonPropertyName("ProductDisplayRanks")]
        public object[] ProductDisplayRanks;

        [JsonPropertyName("InteractiveModelConfig")]
        public object InteractiveModelConfig;

        [JsonPropertyName("Interactive3DEnabled")]
        public bool Interactive3DEnabled;

        [JsonPropertyName("Language")]
        public string Language;

        [JsonPropertyName("Markets")]
        public string[] Markets;

        [JsonPropertyName("ProductConfiguration")]
        public ProductConfiguration ProductConfiguration;
    }
}