// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System.Text.Json.Serialization;

namespace Microsoft.StoreServices.DisplayCatalog.Product
{
    public class MarketProperty
    {
        [JsonPropertyName("OriginalReleaseDate")]
        public string OriginalReleaseDate;

        [JsonPropertyName("OriginalReleaseDateFriendlyName")]
        public string OriginalReleaseDateFriendlyName;

        [JsonPropertyName("MinimumUserAge")]
        public int MinimumUserAge;

        [JsonPropertyName("ContentRatings")]
        public ContentRating[] ContentRatings;

        [JsonPropertyName("RelatedProducts")]
        public RelatedProduct[] RelatedProducts;

        [JsonPropertyName("UsageData")]
        public UsageData[] UsageData;

        [JsonPropertyName("BundleConfig")]
        public BundleConfig BundleConfig;

        [JsonPropertyName("Markets")]
        public string[] Markets;

        [JsonPropertyName("PlannedReleaseDate")]
        public string PlannedReleaseDate;

        [JsonPropertyName("ReleaseDate")]
        public string ReleaseDate;

        [JsonPropertyName("DiscontinuationDate")]
        public string DiscontinuationDate;

        [JsonPropertyName("ProductConfiguration")]
        public ProductConfiguration2 ProductConfiguration;
    }
}