// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System.Text.Json.Serialization;

namespace Microsoft.StoreServices.DisplayCatalog.Product
{
    public class MarketProperty2
    {
        [JsonPropertyName("FirstAvailableDate")]
        public string FirstAvailableDate;

        [JsonPropertyName("SupportedLanguages")]
        public string[] SupportedLanguages;

        [JsonPropertyName("PackageIds")]
        public object PackageIds;

        [JsonPropertyName("PIFilter")]
        public PIFilter PIFilter;

        [JsonPropertyName("Markets")]
        public string[] Markets;

        [JsonPropertyName("Distributors")]
        public object[] Distributors;

        [JsonPropertyName("ConfigurationReferences")]
        public ConfigurationReference[] ConfigurationReferences;
    }
}