// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System.Text.Json.Serialization;

namespace Microsoft.StoreServices.DisplayCatalog.Product
{
    public class OrderManagementData
    {
        [JsonPropertyName("GrantedEntitlementKeys")]
        public object[] GrantedEntitlementKeys;

        [JsonPropertyName("PIFilter")]
        public PIFilter2 PIFilter;

        [JsonPropertyName("Price")]
        public Price Price;
    }
}