// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System.Text.Json.Serialization;

namespace Microsoft.StoreServices.DisplayCatalog.Product
{
    public class Package
    {
        [JsonPropertyName("Applications")]
        public Application[] Applications;

        [JsonPropertyName("Architectures")]
        public string[] Architectures;

        [JsonPropertyName("Capabilities")]
        public string[] Capabilities;

        [JsonPropertyName("DeviceCapabilities")]
        public string[] DeviceCapabilities;

        [JsonPropertyName("ExperienceIds")]
        public object[] ExperienceIds;

        [JsonPropertyName("FrameworkDependencies")]
        public FrameworkDependency[] FrameworkDependencies;

        [JsonPropertyName("HardwareDependencies")]
        public string[] HardwareDependencies;

        [JsonPropertyName("HardwareRequirements")]
        public object[] HardwareRequirements;

        [JsonPropertyName("Hash")]
        public string Hash;

        [JsonPropertyName("HashAlgorithm")]
        public string HashAlgorithm;

        [JsonPropertyName("IsStreamingApp")]
        public bool IsStreamingApp;

        [JsonPropertyName("Languages")]
        public string[] Languages;

        [JsonPropertyName("MaxDownloadSizeInBytes")]
        public object MaxDownloadSizeInBytes;

        [JsonPropertyName("MaxInstallSizeInBytes")]
        public long? MaxInstallSizeInBytes;

        [JsonPropertyName("PackageFormat")]
        public string PackageFormat;

        [JsonPropertyName("PackageFamilyName")]
        public string PackageFamilyName;

        [JsonPropertyName("MainPackageFamilyNameForDlc")]
        public string MainPackageFamilyNameForDlc;

        [JsonPropertyName("PackageFullName")]
        public string PackageFullName;

        [JsonPropertyName("PackageId")]
        public string PackageId;

        [JsonPropertyName("ContentId")]
        public string ContentId;

        [JsonPropertyName("KeyId")]
        public string KeyId;

        [JsonPropertyName("PackageRank")]
        public int PackageRank;

        [JsonPropertyName("PackageUri")]
        public string PackageUri;

        [JsonPropertyName("PlatformDependencies")]
        public PlatformDependency[] PlatformDependencies;

        [JsonPropertyName("PlatformDependencyXmlBlob")]
        public string PlatformDependencyXmlBlob;

        [JsonPropertyName("ResourceId")]
        public string ResourceId;

        [JsonPropertyName("Version")]
        public string Version;

        [JsonPropertyName("PackageDownloadUris")]
        public PackageDownloadUri[] PackageDownloadUris;

        [JsonPropertyName("DriverDependencies")]
        public object[] DriverDependencies;

        [JsonPropertyName("FulfillmentData")]
        public FulfillmentData2 FulfillmentData;
    }
}