// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System.Text.Json.Serialization;

namespace Microsoft.StoreServices.DisplayCatalog.Product
{
    public class PIFilter2
    {
        [JsonPropertyName("ExclusionProperties")]
        public string[] ExclusionProperties;

        [JsonPropertyName("InclusionProperties")]
        public object[] InclusionProperties;
    }
}