// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System.Numerics;
using System.Text.Json.Serialization;

namespace Microsoft.StoreServices.DisplayCatalog.Product
{
    public class PlatformDependency
    {
        /*[JsonPropertyName("MaxTested")]
        public BigInteger MaxTested;

        [JsonPropertyName("MinVersion")]
        public BigInteger MinVersion;*/

        [JsonPropertyName("PlatformName")]
        public string PlatformName;
    }
}