// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System.Text.Json.Serialization;

namespace Microsoft.StoreServices.DisplayCatalog.Product
{
    public class PreviewImage
    {
        [JsonPropertyName("FileId")]
        public string FileId;

        [JsonPropertyName("EISListingIdentifier")]
        public object EISListingIdentifier;

        [JsonPropertyName("BackgroundColor")]
        public object BackgroundColor;

        [JsonPropertyName("Caption")]
        public string Caption;

        [JsonPropertyName("FileSizeInBytes")]
        public int FileSizeInBytes;

        [JsonPropertyName("ForegroundColor")]
        public object ForegroundColor;

        [JsonPropertyName("Height")]
        public int Height;

        [JsonPropertyName("ImagePositionInfo")]
        public object ImagePositionInfo;

        [JsonPropertyName("ImagePurpose")]
        public string ImagePurpose;

        [JsonPropertyName("UnscaledImageSHA256Hash")]
        public string UnscaledImageSHA256Hash;

        [JsonPropertyName("Uri")]
        public string Uri;

        [JsonPropertyName("Width")]
        public int Width;
    }
}