// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System.Text.Json.Serialization;

namespace Microsoft.StoreServices.DisplayCatalog.Product
{
    public class ProductConfigurationProperty2
    {
        [JsonPropertyName("Key")]
        public string Key;

        [JsonPropertyName("SpecificationRenderHint")]
        public string SpecificationRenderHint;

        [JsonPropertyName("DisplayRank")]
        public int DisplayRank;

        [JsonPropertyName("Values")]
        public Value2[] Values;
    }
}