// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System.Text.Json.Serialization;

namespace Microsoft.StoreServices.DisplayCatalog.Product
{
    public class Product
    {
        [JsonPropertyName("LastModifiedDate")]
        public string LastModifiedDate;

        [JsonPropertyName("LocalizedProperties")]
        public LocalizedProperty[] LocalizedProperties;

        [JsonPropertyName("MarketProperties")]
        public MarketProperty[] MarketProperties;

        [JsonPropertyName("ProductASchema")]
        public string ProductASchema;

        [JsonPropertyName("ProductBSchema")]
        public string ProductBSchema;

        [JsonPropertyName("ProductId")]
        public string ProductId;

        [JsonPropertyName("Properties")]
        public Properties Properties;

        [JsonPropertyName("AlternateIds")]
        public AlternateId[] AlternateIds;

        [JsonPropertyName("DomainDataVersion")]
        public object DomainDataVersion;

        [JsonPropertyName("IngestionSource")]
        public string IngestionSource;

        [JsonPropertyName("IsMicrosoftProduct")]
        public bool IsMicrosoftProduct;

        [JsonPropertyName("PreferredSkuId")]
        public string PreferredSkuId;

        [JsonPropertyName("ProductType")]
        public string ProductType;

        [JsonPropertyName("ValidationData")]
        public ValidationData ValidationData;

        [JsonPropertyName("MerchandizingTags")]
        public string[] MerchandizingTags;

        [JsonPropertyName("PartD")]
        public string PartD;

        [JsonPropertyName("ProductFamily")]
        public string ProductFamily;

        [JsonPropertyName("SchemaVersion")]
        public string SchemaVersion;

        [JsonPropertyName("ProductKind")]
        public string ProductKind;

        [JsonPropertyName("DisplaySkuAvailabilities")]
        public DisplaySkuAvailability[] DisplaySkuAvailabilities;

        [JsonPropertyName("SandboxId")]
        public string SandboxId;

        [JsonPropertyName("IsSandboxedProduct")]
        public bool? IsSandboxedProduct;
    }
}