// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System.Text.Json.Serialization;

namespace Microsoft.StoreServices.DisplayCatalog.Product
{
    public class ProductConfiguration
    {
        [JsonPropertyName("Title")]
        public string Title;

        [JsonPropertyName("ShortDescription")]
        public object ShortDescription;

        [JsonPropertyName("ProductConfigurationProperties")]
        public ProductConfigurationProperty[] ProductConfigurationProperties;
    }
}