// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System.Text.Json.Serialization;

namespace Microsoft.StoreServices.DisplayCatalog.Product
{
    public class Properties3
    {
        [JsonPropertyName("OriginalReleaseDate")]
        public string OriginalReleaseDate;

        [JsonPropertyName("PreOrderReleaseDate")]
        public string PreOrderReleaseDate;

        [JsonPropertyName("MerchandisingTags")]
        public string[] MerchandisingTags;
    }
}