// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System.Text.Json.Serialization;

namespace Microsoft.StoreServices.DisplayCatalog.Product
{
    public class Properties
    {
        [JsonPropertyName("Attributes")]
        public Attribute[] Attributes;

        [JsonPropertyName("CanInstallToSDCard")]
        public bool CanInstallToSDCard;

        [JsonPropertyName("Category")]
        public string Category;

        [JsonPropertyName("SubCategory")]
        public string SubCategory;

        [JsonPropertyName("Categories")]
        public string[] Categories;

        [JsonPropertyName("Extensions")]
        public object Extensions;

        [JsonPropertyName("IsAccessible")]
        public bool IsAccessible;

        [JsonPropertyName("IsLineOfBusinessApp")]
        public bool IsLineOfBusinessApp;

        [JsonPropertyName("IsPublishedToLegacyWindowsPhoneStore")]
        public bool IsPublishedToLegacyWindowsPhoneStore;

        [JsonPropertyName("IsPublishedToLegacyWindowsStore")]
        public bool IsPublishedToLegacyWindowsStore;

        [JsonPropertyName("IsSettingsApp")]
        public bool IsSettingsApp;

        [JsonPropertyName("PackageFamilyName")]
        public string PackageFamilyName;

        [JsonPropertyName("PackageIdentityName")]
        public string PackageIdentityName;

        [JsonPropertyName("PublisherCertificateName")]
        public string PublisherCertificateName;

        [JsonPropertyName("PublisherId")]
        public string PublisherId;

        [JsonPropertyName("XboxLiveTier")]
        public string XboxLiveTier;

        [JsonPropertyName("XboxXPA")]
        public object XboxXPA;

        [JsonPropertyName("OwnershipType")]
        public object OwnershipType;

        [JsonPropertyName("PdpBackgroundColor")]
        public string PdpBackgroundColor;

        [JsonPropertyName("HasAddOns")]
        public bool? HasAddOns;

        [JsonPropertyName("RevisionId")]
        public string RevisionId;

        [JsonPropertyName("EntitlementProperties")]
        public object[] EntitlementProperties;

        [JsonPropertyName("ProductGroupId")]
        public string ProductGroupId;

        [JsonPropertyName("ProductGroupName")]
        public string ProductGroupName;

        [JsonPropertyName("IsOmexProduct")]
        public bool? IsOmexProduct;

        [JsonPropertyName("PrimaryCategory")]
        public string PrimaryCategory;

        [JsonPropertyName("Subcategory")]
        public string Subcategory;

        [JsonPropertyName("SkuDisplayGroups")]
        public SkuDisplayGroup[] SkuDisplayGroups;

        [JsonPropertyName("InAppOfferToken")]
        public string InAppOfferToken;

        [JsonPropertyName("IsDemo")]
        public bool? IsDemo;
    }
}