// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System.Text.Json.Serialization;

namespace Microsoft.StoreServices.DisplayCatalog.Product
{
    public class Properties2
    {
        [JsonPropertyName("EarlyAdopterEnrollmentUrl")]
        public object EarlyAdopterEnrollmentUrl;

        [JsonPropertyName("FulfillmentData")]
        public FulfillmentData FulfillmentData;

        [JsonPropertyName("FulfillmentType")]
        public string FulfillmentType;

        [JsonPropertyName("FulfillmentPluginId")]
        public object FulfillmentPluginId;

        [JsonPropertyName("HasThirdPartyIAPs")]
        public bool HasThirdPartyIAPs;

        [JsonPropertyName("LastUpdateDate")]
        public string LastUpdateDate;

        [JsonPropertyName("HardwareProperties")]
        public HardwareProperties HardwareProperties;

        [JsonPropertyName("HardwareRequirements")]
        public object[] HardwareRequirements;

        [JsonPropertyName("HardwareWarningList")]
        public string[] HardwareWarningList;

        [JsonPropertyName("InstallationTerms")]
        public string InstallationTerms;

        [JsonPropertyName("Packages")]
        public Package[] Packages;

        [JsonPropertyName("VersionString")]
        public string VersionString;

        [JsonPropertyName("VisibleToB2BServiceIds")]
        public string[] VisibleToB2BServiceIds;

        [JsonPropertyName("XboxXPA")]
        public bool XboxXPA;

        [JsonPropertyName("BundledSkus")]
        public BundledSku[] BundledSkus;

        [JsonPropertyName("IsRepurchasable")]
        public bool? IsRepurchasable;

        [JsonPropertyName("SkuDisplayRank")]
        public int SkuDisplayRank;

        [JsonPropertyName("DisplayPhysicalStoreInventory")]
        public object DisplayPhysicalStoreInventory;

        [JsonPropertyName("AdditionalIdentifiers")]
        public object[] AdditionalIdentifiers;

        [JsonPropertyName("IsTrial")]
        public bool IsTrial;

        [JsonPropertyName("IsPreOrder")]
        public bool IsPreOrder;

        [JsonPropertyName("IsBundle")]
        public bool IsBundle;

        [JsonPropertyName("Dimensions")]
        public Dimensions Dimensions;

        [JsonPropertyName("Distributions")]
        public Distributions Distributions;

        [JsonPropertyName("ExternalSource")]
        public ExternalSource ExternalSource;

        [JsonPropertyName("InventoryControlSkuId")]
        public string InventoryControlSkuId;

        [JsonPropertyName("MinOrderQuantity")]
        public object MinOrderQuantity;

        [JsonPropertyName("MaxOrderQuantity")]
        public object MaxOrderQuantity;

        [JsonPropertyName("DomainDataReference")]
        public object DomainDataReference;

        [JsonPropertyName("ApplicableLegacyPlatforms")]
        public ApplicableLegacyPlatform[] ApplicableLegacyPlatforms;

        [JsonPropertyName("CustomDeveloperData")]
        public string CustomDeveloperData;

        [JsonPropertyName("MagazineIssueData")]
        public object MagazineIssueData;

        [JsonPropertyName("SkuDisplayGroupIds")]
        public string[] SkuDisplayGroupIds;

        [JsonPropertyName("TrialTimeInSeconds")]
        public int? TrialTimeInSeconds;
    }
}