// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System.Text.Json.Serialization;

namespace Microsoft.StoreServices.DisplayCatalog.Product
{
    public class RelatedProduct
    {
        [JsonPropertyName("RelatedProductId")]
        public string RelatedProductId;

        [JsonPropertyName("RelationshipType")]
        public string RelationshipType;
    }
}