// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System.Text.Json.Serialization;

namespace Microsoft.StoreServices.DisplayCatalog.Product
{
    public class Remediation
    {
        [JsonPropertyName("RemediationId")]
        public string RemediationId;

        [JsonPropertyName("Description")]
        public string Description;
    }
}