// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System.Text.Json.Serialization;

namespace Microsoft.StoreServices.DisplayCatalog.Product
{
    public class Remediation2
    {
        [JsonPropertyName("RemediationId")]
        public string RemediationId;

        [JsonPropertyName("Type")]
        public string Type;

        [JsonPropertyName("Url")]
        public string Url;

        [JsonPropertyName("BigId")]
        public object BigId;

        [JsonPropertyName("CartBasedRemediation")]
        public object CartBasedRemediation;

        [JsonPropertyName("RemediationErrorId")]
        public object RemediationErrorId;
    }
}