// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System.Text.Json.Serialization;

namespace Microsoft.StoreServices.DisplayCatalog.Product
{
    public class SearchTitle
    {
        [JsonPropertyName("SearchTitleString")]
        public string SearchTitleString;

        [JsonPropertyName("SearchTitleType")]
        public string SearchTitleType;
    }
}