// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System.Text.Json.Serialization;

namespace Microsoft.StoreServices.DisplayCatalog.Product
{
    public class Sku
    {
        [JsonPropertyName("LastModifiedDate")]
        public string LastModifiedDate;

        [JsonPropertyName("LocalizedProperties")]
        public LocalizedProperty4[] LocalizedProperties;

        [JsonPropertyName("MarketProperties")]
        public MarketProperty2[] MarketProperties;

        [JsonPropertyName("ProductId")]
        public string ProductId;

        [JsonPropertyName("Properties")]
        public Properties2 Properties;

        [JsonPropertyName("SkuASchema")]
        public string SkuASchema;

        [JsonPropertyName("SkuBSchema")]
        public string SkuBSchema;

        [JsonPropertyName("SkuId")]
        public string SkuId;

        [JsonPropertyName("SkuType")]
        public string SkuType;

        [JsonPropertyName("RecurrencePolicy")]
        public object RecurrencePolicy;

        [JsonPropertyName("SubscriptionPolicyId")]
        public object SubscriptionPolicyId;
    }
}