// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System.Text.Json.Serialization;

namespace Microsoft.StoreServices.DisplayCatalog.Product
{
    public class SkuDisplayRank
    {
        [JsonPropertyName("Dimension")]
        public string Dimension;

        [JsonPropertyName("Rank")]
        public int Rank;
    }
}