// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System.Text.Json.Serialization;

namespace Microsoft.StoreServices.DisplayCatalog.Product
{
    public class StartingFromAmount
    {
        [JsonPropertyName("CurrencyCode")]
        public string CurrencyCode;

        [JsonPropertyName("IsPIRequired")]
        public bool IsPIRequired;

        [JsonPropertyName("ListPrice")]
        public double ListPrice;

        [JsonPropertyName("MSRP")]
        public double MSRP;

        [JsonPropertyName("RecurrencePrice")]
        public double RecurrencePrice;

        [JsonPropertyName("TaxType")]
        public string TaxType;

        [JsonPropertyName("WholesaleCurrencyCode")]
        public string WholesaleCurrencyCode;

        [JsonPropertyName("WholesalePrice")]
        public double WholesalePrice;
    }
}