// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System.Text.Json.Serialization;

namespace Microsoft.StoreServices.DisplayCatalog.Product
{
    public class UsageData
    {
        [JsonPropertyName("AggregateTimeSpan")]
        public string AggregateTimeSpan;

        [JsonPropertyName("AverageRating")]
        public double AverageRating;

        [JsonPropertyName("PlayCount")]
        public double PlayCount;

        [JsonPropertyName("RatingCount")]
        public int RatingCount;

        [JsonPropertyName("RentalCount")]
        public string RentalCount;

        [JsonPropertyName("TrialCount")]
        public string TrialCount;

        [JsonPropertyName("PurchaseCount")]
        public string PurchaseCount;
    }
}