// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System.Text.Json.Serialization;

namespace Microsoft.StoreServices.DisplayCatalog.Product
{
    public class ValidationData
    {
        [JsonPropertyName("PassedValidation")]
        public bool PassedValidation;

        [JsonPropertyName("RevisionId")]
        public string RevisionId;

        [JsonPropertyName("ValidationResultUri")]
        public string ValidationResultUri;
    }
}