// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System.Text.Json.Serialization;

namespace Microsoft.StoreServices.DisplayCatalog.Product
{
    public class Value2
    {
        [JsonPropertyName("Name")]
        public string Name;

        [JsonPropertyName("DisplayRank")]
        public int DisplayRank;

        [JsonPropertyName("IsDefaultSelection")]
        public bool IsDefaultSelection;
    }
}