// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System.Text.Json.Serialization;

namespace Microsoft.StoreServices.DisplayCatalog.Product
{
    public class Value
    {
        [JsonPropertyName("Name")]
        public string Name;

        [JsonPropertyName("Title")]
        public string Title;

        [JsonPropertyName("ShortDescription")]
        public object ShortDescription;

        [JsonPropertyName("Images")]
        public object Images;
    }
}