// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System.Text.Json.Serialization;

namespace Microsoft.StoreServices.DisplayCatalog.Product
{
    public class Video
    {
        [JsonPropertyName("Uri")]
        public string Uri;

        [JsonPropertyName("VideoPurpose")]
        public string VideoPurpose;

        [JsonPropertyName("Height")]
        public int Height;

        [JsonPropertyName("Width")]
        public int Width;

        [JsonPropertyName("AudioEncoding")]
        public string AudioEncoding;

        [JsonPropertyName("VideoEncoding")]
        public string VideoEncoding;

        [JsonPropertyName("VideoPositionInfo")]
        public string VideoPositionInfo;

        [JsonPropertyName("Caption")]
        public string Caption;

        [JsonPropertyName("FileSizeInBytes")]
        public int FileSizeInBytes;

        [JsonPropertyName("PreviewImage")]
        public PreviewImage PreviewImage;

        [JsonPropertyName("SortOrder")]
        public int SortOrder;
    }
}