// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System.Text.Json.Serialization;

namespace Microsoft.StoreServices.DisplayCatalog.Product
{
    public class WebBlendsData
    {
        [JsonPropertyName("ChargeFrequencyString")]
        public object ChargeFrequencyString;

        [JsonPropertyName("CustomWebBlendsText")]
        public object CustomWebBlendsText;

        [JsonPropertyName("Link")]
        public object Link;

        [JsonPropertyName("PurchaseEmailTemplate")]
        public object PurchaseEmailTemplate;

        [JsonPropertyName("TrialDurationString")]
        public object TrialDurationString;
    }
}